# Generated by Django 3.2.2 on 2021-05-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djanpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='login',
            table='20mx119',
        ),
    ]
